# Generated by Django 5.2.4 on 2025-08-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись блога', 'verbose_name_plural': 'Записи блога'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/previews/', verbose_name='Превью'),
        ),
    ]
